/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappHistoryRouteImport } from './routes/_authenticated/whatsapp-history'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMechanicPanelRouteImport } from './routes/_authenticated/mechanic-panel'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedForumRouteImport } from './routes/_authenticated/forum'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated/ai-chat'
import { Route as AuthenticatedGarageIndexRouteImport } from './routes/_authenticated/garage.index'
import { Route as AuthenticatedGarageNewRouteImport } from './routes/_authenticated/garage.new'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappHistoryRoute =
  AuthenticatedWhatsappHistoryRouteImport.update({
    id: '/whatsapp-history',
    path: '/whatsapp-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMechanicPanelRoute =
  AuthenticatedMechanicPanelRouteImport.update({
    id: '/mechanic-panel',
    path: '/mechanic-panel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForumRoute = AuthenticatedForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarageIndexRoute =
  AuthenticatedGarageIndexRouteImport.update({
    id: '/garage/',
    path: '/garage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGarageNewRoute = AuthenticatedGarageNewRouteImport.update({
  id: '/garage/new',
  path: '/garage/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/forum': typeof AuthenticatedForumRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mechanic-panel': typeof AuthenticatedMechanicPanelRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp-history': typeof AuthenticatedWhatsappHistoryRoute
  '/garage/new': typeof AuthenticatedGarageNewRoute
  '/garage/': typeof AuthenticatedGarageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/forum': typeof AuthenticatedForumRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mechanic-panel': typeof AuthenticatedMechanicPanelRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/whatsapp-history': typeof AuthenticatedWhatsappHistoryRoute
  '/garage/new': typeof AuthenticatedGarageNewRoute
  '/garage': typeof AuthenticatedGarageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-chat': typeof AuthenticatedAiChatRoute
  '/_authenticated/forum': typeof AuthenticatedForumRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mechanic-panel': typeof AuthenticatedMechanicPanelRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/whatsapp-history': typeof AuthenticatedWhatsappHistoryRoute
  '/_authenticated/garage/new': typeof AuthenticatedGarageNewRoute
  '/_authenticated/garage/': typeof AuthenticatedGarageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/ai-chat'
    | '/forum'
    | '/home'
    | '/mechanic-panel'
    | '/profile'
    | '/quotes'
    | '/settings'
    | '/whatsapp-history'
    | '/garage/new'
    | '/garage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/ai-chat'
    | '/forum'
    | '/home'
    | '/mechanic-panel'
    | '/profile'
    | '/quotes'
    | '/settings'
    | '/whatsapp-history'
    | '/garage/new'
    | '/garage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/_authenticated/ai-chat'
    | '/_authenticated/forum'
    | '/_authenticated/home'
    | '/_authenticated/mechanic-panel'
    | '/_authenticated/profile'
    | '/_authenticated/quotes'
    | '/_authenticated/settings'
    | '/_authenticated/whatsapp-history'
    | '/_authenticated/garage/new'
    | '/_authenticated/garage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp-history': {
      id: '/_authenticated/whatsapp-history'
      path: '/whatsapp-history'
      fullPath: '/whatsapp-history'
      preLoaderRoute: typeof AuthenticatedWhatsappHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mechanic-panel': {
      id: '/_authenticated/mechanic-panel'
      path: '/mechanic-panel'
      fullPath: '/mechanic-panel'
      preLoaderRoute: typeof AuthenticatedMechanicPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forum': {
      id: '/_authenticated/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof AuthenticatedForumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat': {
      id: '/_authenticated/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garage/': {
      id: '/_authenticated/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof AuthenticatedGarageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garage/new': {
      id: '/_authenticated/garage/new'
      path: '/garage/new'
      fullPath: '/garage/new'
      preLoaderRoute: typeof AuthenticatedGarageNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRoute
  AuthenticatedForumRoute: typeof AuthenticatedForumRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMechanicPanelRoute: typeof AuthenticatedMechanicPanelRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhatsappHistoryRoute: typeof AuthenticatedWhatsappHistoryRoute
  AuthenticatedGarageNewRoute: typeof AuthenticatedGarageNewRoute
  AuthenticatedGarageIndexRoute: typeof AuthenticatedGarageIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiChatRoute: AuthenticatedAiChatRoute,
  AuthenticatedForumRoute: AuthenticatedForumRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMechanicPanelRoute: AuthenticatedMechanicPanelRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhatsappHistoryRoute: AuthenticatedWhatsappHistoryRoute,
  AuthenticatedGarageNewRoute: AuthenticatedGarageNewRoute,
  AuthenticatedGarageIndexRoute: AuthenticatedGarageIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
